### ISSUE TITLE
1.1.0 makes vue-loader error

### ISSUE THREAD

**Issue by TooBug** [vuejs/vue-template-es2015-compiler#2]
version of vue-loader: 9.7.0

```
ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-111583fe!./~/vue-loader/lib/selector.js?type=template&index=0!./component/versions.vue
Module parse failed: /Users/xxx/TooNote/src/node_modules/vue-loader/lib/template-compiler.js?id=data-v-111583fe!/Users/xxx/TooNote/src/node_modules/vue-loader/lib/selector.js?type=template&index=0!/Users/xxx/TooNote/src/component/versions.vue 'with' in strict mode (1:35)
You may need an appropriate loader to handle this file type.
| module.exports={render:function (){with(this) {
|   return _h('section', {
|     directives: [{
 @ ./component/versions.vue 10:23-148
 @ ./main.js
 @ multi main
```

**Comment by yyx990803** [comment]
Webpack seems to incorrectly detect the compiled template code as ES module... reverted in 1.1.1 for now, but would be nice to see the code in question.

**Comment by TooBug** [comment]
Thanks.

90% sure it's because of this package's 1.1.0 version. When I setting up the project on another person's computer, it throws the error below. Then I did `npm ls` on both machine and diffed, and found the version of this package is different. Then I installed the older version manually, everything goes well.  

The source code is here: https://coding.net/u/TooBug/p/TooNote/git/blob/master/src/component/versions.vue

**Comment by yyx990803** [comment]
I see... the line where `v-on:click.stop="()=>{}"` is what causes the problem. Not sure why the transpiled code triggers strict mode in Webpack though...

Actually it can work without the empty function, just like `@click.stop`.

**Comment by TooBug** [comment]
Got it, nice trick! Thx again.

**Comment by Akryum** [comment]
If I enable arrow functions transpiling in bublé, I don't get any webpack error (using webpack 2.1.0-beta.25)
